### ISSUE TITLE
Script errors 

### ISSUE THREAD

**Issue by Nephrem** [jamesthejellyfish/isaac-save-edit-script#2]
Hello and thank a lot for your script, it's totallly what i'm looking for.

I run the script with Python 3.12 64 bits and the script give me a first error :

"NameError: name 'false' is not defined. Did you mean: 'False'?"
I change all the false by False with notepad++

But i've got a second error : 

"NameError: name 'null' is not defined"

And i don't know how to deal with it.

**Comment by jamesthejellyfish** [comment]
um, there shouldn't be any "false" statements in the script. Have you made some changes? Because there aren't any "False" declarations in the original script.

**Comment by Nephrem** [comment]
I made a mistake while editing your script...
I'm sorry for the inconvenience and the issue.
ANd thanks for your work !
