### ISSUE TITLE
Completion Marks Editor

### ISSUE THREAD

**Issue by MRCLARK0** [jamesthejellyfish/isaac-save-edit-script#3]
Hey, not sure if Github has a message functionality, but I was looking to make a Completion Mark editor mod, with the rampent issue of people losing completion marks with the online beta.

I'm a software engineer and I'm pretty certain I could handle the task, but I'm curious how to find the right sections of code to edit in order to make this mod. I would love some insight from you if you wouldn't mind.

My email is mrclark0426@gmail.com

I loved to hear from you! Thanks

**Comment by nyabinary** [comment]
Optimally, there should be a GUI and support for Linux too

**Comment by nyabinary** [comment]
Also, as a victim of the online beta bug, an editor for the donation machine would be nice too

**Comment by jamesthejellyfish** [comment]
Hi! I have significantly altered the script and it now has a GUI and supports donation machine editing, completion mark editing, and other features! @MRCLARK0 I don't know that much about Isaac modding (other than a very basic surface-level understanding), but hopefully if you look at the new script.py file, the offsets and such will help you if you are still pursuing this task.
