### ISSUE TITLE
[Solved] Misc (Donation Machine, Streak) not changeable

### ISSUE THREAD

**Issue by AvengingAngel54** [jamesthejellyfish/isaac-save-edit-script#9]
So when opening a save file the program allows me to "tweak" the values for those parameters such as Donation Machine, Greed Machine, and Win Streak, however, those changes will never save.
If after changing the Donation amount you hit "Unlock all Secrets/Items/Challenges" OR you select a character on the Completion Marks screen (just selecting not even toggling a Completion Mark will do the trick), the value will return to its starting value again.

As such, it's impossible to alter the Eden Tokens or Donation amount.

Here's a video of what I am talking about: **https://imgur.com/a/Az8XVJ6**

It would be really sick if you were able to fix this hiccup.

**Comment by jamesthejellyfish** [comment]
Try pressing enter after you enter the value. I have tested those before and they worked for my so I'm not sure why it wouldn't be working for you.

**Comment by AvengingAngel54** [comment]
Holy smokes I was hoping for a reply within a day or so but 2 minutes?!?

And yes, it's the case. You have to input Enter for it to change the value...

Thank you!
